### PR TITLE
fix settings not merged

### LINKED ISSUE #46: settings are not merged between all and env
When I set controller_settings_all and controller_settings_dev, only the last value wins.
I was expended the variables to be merged.

For instance; 
```yaml
controller_settings_all:
  settings:
    GALAXY_IGNORE_CERTS: true
    AUTH_BASIC_ENABLED: true

controller_settings_dev:
  settings:
    TOWER_URL_BASE: https://aap-control-dev.example.com
```
When using:  `controller_settings: "{{ controller_settings_all | combine(controller_settings_dev, list_merge='append') }}"`
Then `control_settings` become: 

```yaml
settings:
  TOWER_URL_BASE: https://aap-control-dev.example.com
```

I was expecting:

```yaml
settings:
  GALAXY_IGNORE_CERTS: true
  AUTH_BASIC_ENABLED: true
  TOWER_URL_BASE: https://aap-control-dev.example.com
```

### PR DESCRIPTION
**Pull request by laurent-indermuehle**
fix #46 

I'm not sure we can use list_merge with recursive together. Or can we?

### CODE REVIEW

**Comment by j-random-geek** [comment]
I had the same issue and did the same thing to make the settings work in my environment (2 AAP installs - one VM-based, one containerized). Seems to work as expected for me.

**Comment by djdanielsson** [comment]
Did you leave the append or replace it with recursive? @j-random-geek

**Comment by j-random-geek** [comment]
> Did you leave the append or replace it with recursive? @j-random-geek

Sorry, I missed that. I left in the append - this is what's in my own (different environment names, obviously):

`controller_settings: '{{ controller_settings_all | ansible.builtin.combine(controller_settings_vm, list_merge="append", recursive=true) }}'`

**Comment by laurent-indermuehle** [comment]
Great, thanks for your addition @j-random-geek. I'm on vacations for one week. I'll commit this change when I'm back.

**Comment by laurent-indermuehle** [comment]
@djdanielsson I tested to use both list_append and recursive and it seems to work. Thanks @j-random-geek!
I added back list_append to this PR.

**Review by djdanielsson — APPROVED** [review]
LGTM

**Pull request merged**
